version: '3.8'

networks:
  laravel-learning-app-network:
    driver: bridge

volumes:
    mysql-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: learning-laravel-php
    working_dir: /var/www/html
    volumes:
      - ../:/var/www/html
      - ../.env:/var/www/html/.env
    networks:
      - laravel-learning-app-network

  nginx:
    image: nginx:latest
    container_name: learning-laravel-nginx
    ports:
      - "80:80"
    volumes:
      - ../src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-learning-app-network

  mysql:
    image: mysql:8.0
    container_name: learning-laravel-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel-learning
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: laravelpassword
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d
    networks:
      - laravel-learning-app-network


